# Generated by Django 4.1 on 2022-09-02 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppMetal', '0002_graduados'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bandas',
            new_name='Grupos',
        ),
    ]
