# Generated by Django 4.1 on 2022-09-04 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppMetal', '0005_curso_rename_ingresante_ingresantes_delete_grupos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graduados',
            name='fecha_graduacion',
        ),
        migrations.RemoveField(
            model_name='ingresantes',
            name='fecha_nacimiento',
        ),
    ]
