# Generated by Django 4.1 on 2022-09-04 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMetal', '0006_remove_graduados_fecha_graduacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('asignacion', models.IntegerField()),
            ],
        ),
    ]
