# Generated by Django 4.1 on 2022-09-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMetal', '0007_banda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bandas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('numero', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Banda',
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
    ]
