# Generated by Django 4.1 on 2022-09-05 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppMetal', '0008_bandas_delete_banda_delete_curso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bandas',
            old_name='numero',
            new_name='comision',
        ),
    ]
