# Generated by Django 4.1 on 2022-09-07 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMetal', '0009_rename_numero_bandas_comision'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandas',
            name='genero',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='graduados',
            name='instrumento',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingresantes',
            name='instrumento',
            field=models.CharField(default='voz', max_length=50),
            preserve_default=False,
        ),
    ]
