# Generated by Django 4.1 on 2022-09-07 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppMetal', '0010_bandas_genero_graduados_instrumento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bandas',
            name='genero',
        ),
    ]
